---
title: "Analysis of Squamate Species Tree"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

\`\`\`{r setup, include=FALSE} knitr::opts_chunk\$set(echo = TRUE)

# Set the working directory and load the main script

source("\~/bin/OliveTrees/OliveTree/R/OliveTree.R")
setwd("\~/Documents/OliveTrees")

# Load the squamate tree data

squamate_tree \<- read_tree(input_file =
"squamates_Title_Science2024_ultrametric_constrained.tre")

# Visualize the tree in a circular format

visualize_tree( tree = squamate_tree, form = "circular", tiplabels =
TRUE, tip_label_size = 1, bootstrap_numbers = TRUE, bootstrap_circles =
FALSE, bootstrap_number_nudge_x = 0, bootstrap_number_nudge_y = 0.4,
save = FALSE )

# Show tip labels for species with pattern "Crotalus" and save the output

visualize_tree( tree = squamate_tree, form = "circular", tiplabels =
TRUE, pattern_id = "Crotalus", save = TRUE, output =
"whole_squamate_tree_with_Crotalus.svg" )

# Load the full species taxonomy

squamates \<- read.csv("squamateTreetaxa.csv")

# Define the families of snakes and lizards

snake_families \<- c("Acrochordidae", "Aniliidae", "Anomalepididae",
"Anomochilidae", ...) lizard_families \<- c("Agamidae",
"Alopoglossidae", "Amphisbaenidae", "Anguidae", ...)

# Extract snakes and lizards based on family names

snakes \<- unlist(sapply(snake_families, function(family) {
squamates[grepl(family, squamates[,'family']),][,1] }))

lizards \<- unlist(sapply(lizard_families, function(family) {
squamates[grepl(family, squamates[,'family']),][,1] }))

# Define highlight nodes

highlight_nodes = c("Snakes" = 6890, "Lizards" = 8983)

# Highlight the nodes and save the visualized tree

highlight_tree( squamate_tree, form = "circular", highlight_nodes =
highlight_nodes, colors = c("Snakes"= "red3", "Lizards" = "green4"),
save = TRUE, output = "Squamate_tree_highlighted.svg" )

# Extract the Crotalus genus subtree

crotalus_species \<- squamates[grepl('Crotalus',
squamates[,'genus']),][,1] crotalus_subtree \<- extract_subtree(tree =
squamate_tree, taxon_list = crotalus_species)

# Visualize the Crotalus subtree

visualize_tree( crotalus_subtree, form = "circular", tiplabels = TRUE,
tip_label_size = 4, save = TRUE, output = "Crotalus_tree.svg" )
